// Bu dosyadaki ürünleri düzenleyerek katalog fiyatlarını, stok durumunu ve görselleri yönetebilirsiniz.
window.BUKETIA_PRODUCTS = [
  {
    id: "romantik-pudra",
    name: "Romantik Pudra",
    category: "Buket",
    categories: ["Buket", "Sevgiliye"],
    price: 1850,
    description: "Pudra tonlarında mevsim çiçekleri ve zarif yeşilliklerle hazırlanan imza buket.",
    image: "assets/urunler/romantik-pudra.jpg",
    tone: "rose",
    badge: "Çok sevilen",
    inStock: true
  },
  {
    id: "ask-kirmizi",
    name: "Derin Aşk",
    category: "Buket",
    categories: ["Buket", "Sevgiliye"],
    price: 2750,
    description: "Kırmızı güller ve bordo dokularla hazırlanan güçlü, modern bir buket.",
    image: "assets/urunler/ask-kirmizi.jpg",
    tone: "wine",
    badge: "İmza tasarım",
    inStock: true
  },
  {
    id: "fusya-ruya",
    name: "Fuşya Rüya",
    category: "Buket",
    categories: ["Buket", "Sevgiliye"],
    description: "Fuşya ambalajda gladiol, krizantem ve güllerle hazırlanan canlı, gösterişli bir buket.",
    image: "assets/urunler/fusya-ruya.jpg",
    tone: "rose",
    badge: "",
    inStock: true
  },
  {
    id: "iyi-hisset",
    name: "İyi Hisset",
    category: "Buket",
    categories: ["Buket"],
    price: 1650,
    description: "Açık sarı ve beyaz tonlarıyla iç açan, yumuşak dokulu mevsim buketi.",
    image: "assets/urunler/iyi-hisset.jpg",
    tone: "sun",
    badge: "Mevsim seçkisi",
    inStock: true
  },
  {
    id: "kirmizi-kalp",
    name: "Kırmızı Kalp",
    category: "Buket",
    categories: ["Buket", "Sevgiliye"],
    description: "Kırmızı güllerle kalp şeklinde hazırlanan, unutulmaz bir sevgi aranjmanı.",
    image: "assets/urunler/kirmizi-kalp.jpg",
    tone: "wine",
    badge: "",
    inStock: true
  },
  {
    id: "pembe-masal",
    name: "Pembe Masal",
    category: "Buket",
    categories: ["Buket", "Sevgiliye"],
    description: "Pembe gül, alstroemeria ve lilyumların krem ambalajda buluştuğu romantik bir buket.",
    image: "assets/urunler/pembe-masal.jpg",
    tone: "rose",
    badge: "",
    inStock: true
  },
  {
    id: "yeni-baslangic",
    name: "Yeni Başlangıç",
    category: "Buket",
    categories: ["Buket"],
    price: 2100,
    description: "Modern kutuda beyaz ve yeşil çiçeklerle hazırlanan kutlama aranjmanı.",
    image: "assets/urunler/yeni-baslangic.jpg",
    tone: "green",
    badge: "Ofise uygun",
    inStock: true
  },
  {
    id: "mercan-guller",
    name: "Mercan Güller",
    category: "Buket",
    categories: ["Buket", "Sevgiliye"],
    description: "Mercan ve krem tonlarında güller, cipsofilyayla birlikte doğal hasır ambalajda.",
    image: "assets/urunler/mercan-guller.jpg",
    tone: "rose",
    badge: "",
    inStock: true
  },
  {
    id: "pastel-kutlama",
    name: "Pastel Kutlama",
    category: "Buket",
    categories: ["Buket"],
    price: 1950,
    description: "Pastel tonlarda hacimli çiçeklerle hazırlanan neşeli doğum günü aranjmanı.",
    image: "assets/urunler/pastel-kutlama.jpg",
    tone: "lilac",
    badge: "Sınırlı sayıda",
    inStock: true
  },
  {
    id: "isme-ozel-gul-kutusu",
    name: "İsme Özel Gül Kutusu",
    category: "Özel Aranjman",
    categories: ["Özel Aranjman", "Sevgiliye"],
    description: "Şeffaf kutuda kırmızı güller ve sevdiğinizin ismiyle hazırlanan kişiye özel tasarım.",
    image: "assets/urunler/isme-ozel-gul-kutusu.jpg",
    tone: "wine",
    badge: "İsme özel",
    inStock: true
  },
  {
    id: "gunesli-gun",
    name: "Güneşli Gün",
    category: "Buket",
    categories: ["Buket"],
    description: "Ayçiçekleri ve turuncu güllerle hazırlanan, yüzleri güldüren bir buket.",
    image: "assets/urunler/gunesli-gun.jpg",
    tone: "sun",
    badge: "",
    inStock: true
  },
  {
    id: "beyaz-lilyum",
    name: "Beyaz Lilyum",
    category: "Buket",
    categories: ["Buket"],
    description: "Beyaz lilyumlar ve pembe güllerle hazırlanan ferah, zarif bir buket.",
    image: "assets/urunler/beyaz-lilyum.jpg",
    tone: "ivory",
    badge: "",
    inStock: true
  },
  {
    id: "bahar-sepeti",
    name: "Bahar Sepeti",
    category: "Özel Aranjman",
    categories: ["Özel Aranjman"],
    description: "Hasır sepette gerbera, lilyum ve krizantemlerle hazırlanan neşeli bir aranjman.",
    image: "assets/urunler/bahar-sepeti.jpg",
    tone: "sun",
    badge: "",
    inStock: true
  },
  {
    id: "lavanta-bahcesi",
    name: "Lavanta Bahçesi",
    category: "Buket",
    categories: ["Buket", "Sevgiliye"],
    description: "Mor ambalajda pembe güller ve mevsim çiçekleriyle hazırlanan zarif bir buket.",
    image: "assets/urunler/lavanta-bahcesi.jpg",
    tone: "lilac",
    badge: "",
    inStock: true
  },
  {
    id: "altin-gece",
    name: "Altın Gece",
    category: "Buket",
    categories: ["Buket"],
    description: "Siyah ve altın ambalajda lilyum ve renkli mevsim çiçekleriyle hazırlanan şık bir buket.",
    image: "assets/urunler/altin-gece.jpg",
    tone: "stone",
    badge: "",
    inStock: true
  },
  {
    id: "kir-esintisi",
    name: "Kır Esintisi",
    category: "Buket",
    categories: ["Buket"],
    description: "Lilyum ile mavi ve sarı mevsim çiçeklerinden hazırlanan doğal, renkli bir buket.",
    image: "assets/urunler/kir-esintisi.jpg",
    tone: "pearl",
    badge: "",
    inStock: true
  },
  {
    id: "mor-melodi",
    name: "Mor Melodi",
    category: "Buket",
    categories: ["Buket"],
    description: "Mor ambalajda pembe lilyumlar ve renkli mevsim çiçekleriyle hazırlanan neşeli bir buket.",
    image: "assets/urunler/mor-melodi.jpg",
    tone: "lilac",
    badge: "",
    inStock: true
  },
  {
    id: "orman-buketi",
    name: "Orman Buketi",
    category: "Buket",
    categories: ["Buket"],
    description: "Koyu yeşil ambalajda lilyum ve mevsim çiçekleriyle hazırlanan doğal, canlı bir buket.",
    image: "assets/urunler/orman-buketi.jpg",
    tone: "green",
    badge: "",
    inStock: true
  },
  {
    id: "gri-zarafet",
    name: "Gri Zarafet",
    category: "Buket",
    categories: ["Buket"],
    description: "Gri ambalajda lilyum, karanfil ve renkli çiçeklerle hazırlanan modern bir buket.",
    image: "assets/urunler/gri-zarafet.jpg",
    tone: "stone",
    badge: "",
    inStock: true
  },
  {
    id: "beyaz-ruya",
    name: "Beyaz Rüya",
    category: "Buket",
    categories: ["Buket"],
    description: "Beyaz ambalajda pembe lilyum ve mevsim çiçekleriyle hazırlanan zarif bir buket.",
    image: "assets/urunler/beyaz-ruya.jpg",
    tone: "ivory",
    badge: "",
    inStock: true
  },
  {
    id: "yaz-senligi",
    name: "Yaz Şenliği",
    category: "Buket",
    categories: ["Buket"],
    description: "Rengârenk alstroemeria, lilyum ve karanfillerle hazırlanan neşeli bir buket.",
    image: "assets/urunler/yaz-senligi.jpg",
    tone: "rose",
    badge: "",
    inStock: true
  },
  {
    id: "mutluluk-sepeti",
    name: "Mutluluk Sepeti",
    category: "Özel Aranjman",
    categories: ["Özel Aranjman"],
    description: "Hasır sepette gerbera, lilyum ve renkli çiçeklerle hazırlanan bir mutluluk aranjmanı.",
    image: "",
    tone: "sun",
    badge: "",
    inStock: true
  },
  {
    id: "bohem-sepet",
    name: "Bohem Sepet",
    category: "Özel Aranjman",
    categories: ["Özel Aranjman"],
    description: "Ortanca, gül ve sarkan amarantlarla hasır sepette hazırlanan bohem bir aranjman.",
    image: "assets/urunler/bohem-sepet.jpg",
    tone: "wine",
    badge: "Özel tasarım",
    inStock: true
  },
  {
    id: "beyaz-orkide",
    name: "Saf Zarafet Orkide",
    category: "Orkide",
    categories: ["Orkide"],
    price: 2450,
    description: "Mat seramik saksıda, uzun ömürlü ve zarif beyaz çift dallı orkide.",
    image: "",
    tone: "ivory",
    badge: "Yeni",
    inStock: true
  },
  {
    id: "gelin-inci",
    name: "İnci Gelin Buketi",
    category: "Buket",
    categories: ["Buket"],
    price: 3250,
    description: "Beyaz tonların katmanlı dokusuyla hazırlanan zamansız gelin buketi.",
    image: "",
    tone: "pearl",
    badge: "Özel tasarım",
    inStock: true
  },
  {
    id: "celenk-01",
    name: "Mavi Bahçe Çelengi",
    category: "Çelenk",
    categories: ["Çelenk"],
    description: "Beyaz gerbera ve sarı aslanağzı ile hazırlanan ayaklı çiçek aranjmanı. Şerit yazısı isteğe göre hazırlanır.",
    image: "assets/urunler/celenk-01.jpg",
    tone: "stone",
    badge: "",
    inStock: true
  },
  {
    id: "celenk-02",
    name: "Zümrüt Altın Çelengi",
    category: "Çelenk",
    categories: ["Çelenk"],
    description: "Beyaz papatya ve gerbera ile hazırlanan ayaklı çiçek aranjmanı. Şerit yazısı isteğe göre hazırlanır.",
    image: "assets/urunler/celenk-02.jpg",
    tone: "sage",
    badge: "",
    inStock: true
  },
  {
    id: "celenk-03",
    name: "Güneş Mavisi Çelengi",
    category: "Çelenk",
    categories: ["Çelenk"],
    description: "Sarı gerbera ve pembe detaylar ile hazırlanan ayaklı çiçek aranjmanı. Şerit yazısı isteğe göre hazırlanır.",
    image: "assets/urunler/celenk-03.jpg",
    tone: "sun",
    badge: "",
    inStock: true
  },
  {
    id: "celenk-04",
    name: "Gri Mavi Çelengi",
    category: "Çelenk",
    categories: ["Çelenk"],
    description: "Beyaz gerbera ve yeşillikler ile hazırlanan ayaklı çiçek aranjmanı. Şerit yazısı isteğe göre hazırlanır.",
    image: "assets/urunler/celenk-04.jpg",
    tone: "pearl",
    badge: "",
    inStock: true
  },
  {
    id: "celenk-05",
    name: "Altın Sarı Damla Çelengi",
    category: "Çelenk",
    categories: ["Çelenk"],
    description: "Sarı krizantem ile hazırlanan damla ayaklı çelenk. Şerit yazısı isteğe göre hazırlanır.",
    image: "assets/urunler/celenk-05.jpg",
    tone: "sun",
    badge: "",
    inStock: true
  },
  {
    id: "celenk-06",
    name: "Güneş Damla Çelengi",
    category: "Çelenk",
    categories: ["Çelenk"],
    description: "Sarı ve turuncu gerbera ile hazırlanan damla ayaklı çelenk. Şerit yazısı isteğe göre hazırlanır.",
    image: "assets/urunler/celenk-06.jpg",
    tone: "sun",
    badge: "",
    inStock: true
  },
  {
    id: "celenk-07",
    name: "Siyah Yuvarlak Çelengi",
    category: "Çelenk",
    categories: ["Çelenk"],
    description: "Kırmızı ve sarı gerbera ile hazırlanan yuvarlak ayaklı çelenk. Şerit yazısı isteğe göre hazırlanır.",
    image: "assets/urunler/celenk-07.jpg",
    tone: "stone",
    badge: "",
    inStock: true
  },
  {
    id: "celenk-08",
    name: "Siyah Halka Çelengi",
    category: "Çelenk",
    categories: ["Çelenk"],
    description: "Kırmızı gerbera ve krem çiçekler ile hazırlanan yuvarlak ayaklı çelenk. Şerit yazısı isteğe göre hazırlanır.",
    image: "assets/urunler/celenk-08.jpg",
    tone: "stone",
    badge: "",
    inStock: true
  },
  {
    id: "celenk-09",
    name: "Sarı Papatya Damla Çelengi",
    category: "Çelenk",
    categories: ["Çelenk"],
    description: "Sarı papatya ve gerbera ile hazırlanan damla ayaklı çelenk. Şerit yazısı isteğe göre hazırlanır.",
    image: "assets/urunler/celenk-09.jpg",
    tone: "sun",
    badge: "",
    inStock: true
  },
  {
    id: "celenk-10",
    name: "Kırmızı Beyaz Damla Çelengi",
    category: "Çelenk",
    categories: ["Çelenk"],
    description: "Kırmızı ve beyaz gerbera ile hazırlanan damla ayaklı çelenk. Şerit yazısı isteğe göre hazırlanır.",
    image: "assets/urunler/celenk-10.jpg",
    tone: "rose",
    badge: "",
    inStock: true
  },
  {
    id: "celenk-11",
    name: "Sarı Çift Katlı Çelengi",
    category: "Çelenk",
    categories: ["Çelenk"],
    description: "Sarı krizantem ile hazırlanan çift katlı ayaklı çelenk. Şerit yazısı isteğe göre hazırlanır.",
    image: "assets/urunler/celenk-11.jpg",
    tone: "sun",
    badge: "",
    inStock: true
  },
  {
    id: "celenk-12",
    name: "Kırmızı Beyaz Saygı Çelengi",
    category: "Çelenk",
    categories: ["Çelenk"],
    description: "Kırmızı karanfil ve beyaz papatya ile hazırlanan damla ayaklı çelenk. Şerit yazısı isteğe göre hazırlanır.",
    image: "assets/urunler/celenk-12.jpg",
    tone: "rose",
    badge: "",
    inStock: true
  },
  {
    id: "celenk-13",
    name: "Kırmızı Gerbera Damla Çelengi",
    category: "Çelenk",
    categories: ["Çelenk"],
    description: "Kırmızı gerbera ile hazırlanan damla ayaklı çelenk. Şerit yazısı isteğe göre hazırlanır.",
    image: "assets/urunler/celenk-13.jpg",
    tone: "rose",
    badge: "",
    inStock: true
  },
  {
    id: "celenk-14",
    name: "Yeşil Kenarlı Renkli Çelengi",
    category: "Çelenk",
    categories: ["Çelenk"],
    description: "Sarı krizantem ve pembe gerbera ile hazırlanan damla ayaklı çelenk. Şerit yazısı isteğe göre hazırlanır.",
    image: "assets/urunler/celenk-14.jpg",
    tone: "sage",
    badge: "",
    inStock: true
  },
  {
    id: "celenk-15",
    name: "Üç Renkli Damla Çelengi",
    category: "Çelenk",
    categories: ["Çelenk"],
    description: "Kırmızı, sarı ve beyaz gerbera ile hazırlanan damla ayaklı çelenk. Şerit yazısı isteğe göre hazırlanır.",
    image: "assets/urunler/celenk-15.jpg",
    tone: "rose",
    badge: "",
    inStock: true
  },
  {
    id: "celenk-16",
    name: "Beyaz Kırmızı Kıvrım Çelengi",
    category: "Çelenk",
    categories: ["Çelenk"],
    description: "Krem gerbera ve kırmızı detaylar ile hazırlanan damla ayaklı çelenk. Şerit yazısı isteğe göre hazırlanır.",
    image: "assets/urunler/celenk-16.jpg",
    tone: "rose",
    badge: "",
    inStock: true
  },
  {
    id: "celenk-17",
    name: "Krem Gerbera Çelengi",
    category: "Çelenk",
    categories: ["Çelenk"],
    description: "Krem gerbera ile hazırlanan damla ayaklı çelenk. Şerit yazısı isteğe göre hazırlanır.",
    image: "assets/urunler/celenk-17.jpg",
    tone: "ivory",
    badge: "",
    inStock: true
  },
  {
    id: "celenk-18",
    name: "Beyaz Çift Katlı Çelengi",
    category: "Çelenk",
    categories: ["Çelenk"],
    description: "Krem gerbera ve papatya ile hazırlanan çift katlı ayaklı çelenk. Şerit yazısı isteğe göre hazırlanır.",
    image: "assets/urunler/celenk-18.jpg",
    tone: "ivory",
    badge: "",
    inStock: true
  },
  {
    id: "celenk-19",
    name: "Kırmızı Beyaz Çapraz Çelengi",
    category: "Çelenk",
    categories: ["Çelenk"],
    description: "Kırmızı ve beyaz gerbera ile hazırlanan damla ayaklı çelenk. Şerit yazısı isteğe göre hazırlanır.",
    image: "assets/urunler/celenk-19.jpg",
    tone: "rose",
    badge: "",
    inStock: true
  },
  {
    id: "celenk-20",
    name: "Kırmızı Beyaz Armut Çelengi",
    category: "Çelenk",
    categories: ["Çelenk"],
    description: "Kırmızı güller ve beyaz papatya ile hazırlanan damla ayaklı çelenk. Şerit yazısı isteğe göre hazırlanır.",
    image: "assets/urunler/celenk-20.jpg",
    tone: "rose",
    badge: "",
    inStock: true
  },
  {
    id: "celenk-21",
    name: "Krem Papatya Çelengi",
    category: "Çelenk",
    categories: ["Çelenk"],
    description: "Krem papatya ve gerbera ile hazırlanan damla ayaklı çelenk. Şerit yazısı isteğe göre hazırlanır.",
    image: "assets/urunler/celenk-21.jpg",
    tone: "ivory",
    badge: "",
    inStock: true
  }
];
